version: "3"
services:
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/Dev/docker/volumes/neo4j/data:/data
      - $HOME/Dev/docker/volumes/neo4j/logs:/logs
      - $HOME/Dev/docker/volumes/neo4j/plugins:/plugins
      - $HOME/Dev/docker/volumes/neo4j/import:/import
    environment:
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_dbms.connectors.default_listen_address=127.0.0.1
      - NEO4J_dbms.security.auth_enabled=false
      - NEO4J_dbms.security.procedures.unrestricted=apoc.*
      - NEO4JLABS_PLUGINS=["apoc\"]
