version: "3.1"

services:
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "docker"
    ports:
      - "3306:3306"
    volumes:
      - $HOME/Dev/docker/volumes/mysql:/var/lib/mysql
    network_mode: "bridge"
