version: "3.8"
services:
  db:
    container_name: mongo
    image: mongo:latest
    restart: on-failure
    volumes:
      - $HOME/Dev/docker/volumes/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - "27017:27017"
    network_mode: "bridge"
